// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BAvatar: typeof import('bootstrap-vue-3')['BAvatar']
    BAvatarGroup: typeof import('bootstrap-vue-3')['BAvatarGroup']
    BBadge: typeof import('bootstrap-vue-3')['BBadge']
    BBreadcrumb: typeof import('bootstrap-vue-3')['BBreadcrumb']
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BCard: typeof import('bootstrap-vue-3')['BCard']
    BCardBody: typeof import('bootstrap-vue-3')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-3')['BCardHeader']
    BCardText: typeof import('bootstrap-vue-3')['BCardText']
    BCol: typeof import('bootstrap-vue-3')['BCol']
    BCollapse: typeof import('bootstrap-vue-3')['BCollapse']
    BContainer: typeof import('bootstrap-vue-3')['BContainer']
    BDropdownItem: typeof import('bootstrap-vue-3')['BDropdownItem']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    BIcon: typeof import('bootstrap-vue-3')['BIcon']
    BImg: typeof import('bootstrap-vue-3')['BImg']
    BNav: typeof import('bootstrap-vue-3')['BNav']
    BNavbar: typeof import('bootstrap-vue-3')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-3')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-3')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-3')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue-3')['BNavForm']
    BNavItem: typeof import('bootstrap-vue-3')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-3')['BNavItemDropdown']
    BRow: typeof import('bootstrap-vue-3')['BRow']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-3')['VBToggle']
  }
}
